export const categoryJobs: Record<string, string> = {
    'Software Development': "Desarrollo de software",
    'Customer Service': "Servicio al cliente",
    Design: "Diseño",
    Sales: "Ventas",
    'Product Management': "Gestión de productos",
    'Project Management': "Gestión de proyectos",
    'Artificial Intelligence': "Inteligencia Artificial",
    'Data and Analytics': "Datos y análisis",
    Devops: "DevOps",
    Finance: "Finanzas",
    'Human Resources': "Recursos humanos",
    'Quality Assurance': "QA",
    Writing: "Escritura",
    Medical: "Medicina",
    Teaching: "Profesor",
    'Account Management': "Gestión de cuentas",
    'Business Development': "Desarrollo empresarial",
    Communications: "Comunicación",
    Engineering: 'Ingeniería',
    'Information Technology': "Tecnologías de la información",
    'Knowledge Management': "Gestión del conocimiento",
    Operations: "Operaciones",
    Research: "Investigación",
    Strategy: "Estrategia",
    'Supply Chain': "Cadena de suministro",
    'Travel and Hospitality': "Viajes y hostelería",
    'All others': "Otros"
};
